config/routes.rb
Blog::Application.routes.draw do
  resources :appointments

  resources :appointments, only: [:index, :show]

  get "/appointments" => "appointment#index"
  
  get "csc667/index"
  get "csc667/project0"
  get "csc667/project1"
  get "csc667/project2"
  get "csc667/project3"

  root to: "csc667#index"

  

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authencity_token
  
  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:month, :year, :date, :time, :desc)
    end
end

app/controllers/csc667_controller.rb
class Csc667Controller < ApplicationController
  def index
  end
  
  def project0
  end

  def project1
  end
  
  def project2
  end
  
  def project3
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/csc667_helper.rb
module Csc667Helper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.number_field :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.number_field :time %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Month</th>
      <th>Year</th>
      <th>Date</th>
      <th>Time</th>
      <th>Desc</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.month %></td>
        <td><%= appointment.year %></td>
        <td><%= appointment.date %></td>
        <td><%= appointment.time %></td>
        <td><%= appointment.desc %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Month:</strong>
  <%= @appointment.month %>
</p>

<p>
  <strong>Year:</strong>
  <%= @appointment.year %>
</p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @appointment.desc %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

app/views/csc667/index.html.erb
<html>
	<h1>Victor Tam</h1>

	<table>
		<tr>
			<th><b>Project Name</b></th>
			<th><b>Description</b></th>
			<th><b>URL</b></th>
		</tr>
	
	<% number = 0 %> 
	<% PROJECTS.each do |project, descript, url| %>
		<tr>
			<td><%= project %></td>
			<td><%= descript['description'] %></td>
			<td><%= link_to descript['url'], controller => "project#{number}", :action => "project#{number}"%></td>
			<% number += 1 %>
		</tr>
	<% end %>

	</table>
</html>	

app/views/csc667/project0.html.erb
<h1>Project 0</h1>

app/views/csc667/project1.html.erb
<h1>Project 1</h1>

app/views/csc667/project2.html.erb
<h1>Project 2</h1>
<p>-Install ruby gem 'bootstrap-sass'.</p>
<p>-Add "@import bootstrap" to the csc667.css.scss.</p>
<p>-In addition, added several css code to test on own website.</p>
<p>-Add and commit to heroku.</p>

app/views/csc667/project3.html.erb
<!DOCTYPE html>
<html>
<title>Web Page Design</title>
<head>
<h1>Project 3</h1>

<%= javascript_include_tag('calendar.js') %>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
</head>

<body>

<p>Time</p>
<select id = "time">
	<option value="12:00AM">12:00AM</option>
	<option value="1:00AM">1:00AM</option>
	<option value="2:00AM">2:00AM</option>
	<option value="3:00AM">3:00AM</option>
	<option value="4:00AM">4:00AM</option>
	<option value="5:00AM">5:00AM</option>
	<option value="6:00AM">6:00AM</option>
	<option value="7:00AM">7:00AM</option>
	<option value="8:00AM">8:00AM</option>
	<option value="9:00AM">9:00AM</option>
	<option value="10:00AM">10:00AM</option>
	<option value="11:00AM">11:00AM</option>
	<option value="12:00PM">12:00PM</option>
	<option value="1:00PM">1:00PM</option>
	<option value="2:00PM">2:00PM</option>
	<option value="3:00PM">3:00PM</option>
	<option value="4:00PM">4:00PM</option>
	<option value="5:00PM">5:00PM</option>
	<option value="6:00PM">6:00PM</option>
	<option value="7:00PM">7:00PM</option>
	<option value="8:00PM">8:00PM</option>
	<option value="9:00PM">9:00PM</option>
	<option value="10:00PM">10:00PM</option>
	<option value="11:00PM">11:00PM</option>
</select> 

<p>Description</p>
<form name="input">
<input type="text" id="descript" required><br>
<input type="button" onclick="add_info()" value="Update">
</form> 

<button type="button" onclick="change_date('<<')"><<</button>
<button type="button" onclick="change_date('<')"><</button>
<button type="button" onclick="change_date('>>')" style='float: right;'>>></button>
<button type="button" onclick="change_date('>')" style='float: right;'>></button>

<div id="calendar"><script language = "javascript">fill_calendar(monthName[monthNum - 1], numDays)</script></div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>